
services:
  server:
    build:
      dockerfile: Dockerfile.dev
    image: manulangat/blog_by_langat:jobzy
    env_file:
      - .env
    ports:
      - 3002:3002
    networks:
      - webnet

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: manulangat/blog_by_langat:jobzy-be-nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #   restart: always


# networks:
#   webnet:
#     external: true
  
    

  


